
# NON GRADED DESCRIPTIVE STATISTIC


Muhammad Farhan Zahirsyah

Batch 10

---

## ASSIGNMENT INSTRUCTIONS
- Find Measure of Central Tendency from the dataset.
- Find Measure of Variance from the dataset.

### Import library

In [46]:
import pandas as pd
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt


%matplotlib inline

## Data Exploration

In [47]:
covid_df = pd.read_csv('covid_19_indonesia_time_series_all.csv')

In [48]:
covid_df.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,41,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,105.13%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,41,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,100.00%,1.0,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,2,0,3,...,0.511648,0.16,0.33,0.0,0.00,0.00,0.00%,150.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,41,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,95.35%,1.0,1.0

In [49]:
covid_df.shape

(21759, 38)

In [50]:
num_columns = covid_df.select_dtypes(include=np.number).columns.tolist()
obj_columns = covid_df.select_dtypes(include=['object']).columns.tolist()

In [51]:
covid_df[num_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
New Cases,21759.0,3.912936e+02,2.074551e+03,0.000000,7.000000e+00,4.100000e+01,1.510000e+02,5.675700e+04
New Deaths,21759.0,1.322041e+01,7.648262e+01,0.000000,0.000000e+00,1.000000e+00,5.000000e+00,2.069000e+03
New Recovered,21759.0,3.773110e+02,1.999063e+03,0.000000,4.000000e+00,3.100000e+01,1.430000e+02,4.883200e+04
New Active Cases,21759.0,7.621674e-01,9.372135e+02,-25725.000000,-1.600000e+01,0.000000e+00,2.700000e+01,3.672600e+04
Total Cases,21759.0,8.525997e+04,3.685133e+05,1.000000,1.822500e+03,1.078000e+04,3.646450e+04,4.257243e+06
Total Deaths,21759.0,2.648289e+03,1.177601e+04,0.000000,5.000000e+01,2.830000e+02,1.050000e+03,1.438580e+05
Total Recovered,21759.0,7.671260e+04,3.403957e+05,0.000000,1.038500e+03,8.745000e+03,3.293250e+04,4.105680e+06
Total Active Cases,21759.0,5.899079e+03,2.751810e+04,-2306.000000,1.820000e+02,9.190000e+02,2.607500e+03,5.741350e+05
City or Regency,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Regencies,21759.0,2.416026e+01,6.870827e+01,1.000000,7.000000e+00,1.100000e+01,1.800000e+01,4.160000e+02
Total Cities,21145.0,5.872499e+00,1.647141e+01,1.000000,1.000000e+00,2.000000e+00,4.000000e+00,9.800000e+01
Total Districts,21759.0,4.204444e+02,1.199019e+03,44.000000,1.030000e+02,1.690000e+02,2.890000e+02,7.230000e+03
Total Urban Villages,21142.0,5.087405e+02,1.429128e+03,35.000000,9.900000e+01,1.750000e+02,3.320000e+02,8.488000e+03
Total Rural Villages,21117.0,4.490348e+03,1.264756e+04,275.000000,9.280000e+02,1.591000e+03,2.853000e+03,7.495300e+04
Area (km2),21759.0,1.112418e+05,3.203746e+05,664.000000,1.678700e+04,4.201300e+04,7.546800e+04,1.916907e+06
Population,21759.0,1.547817e+07,4.483574e+07,648407.000000,1.999539e+06,4.216171e+06,9.095591e+06,2.651855e+08
Population Density,21759.0,7.449898e+02,2.743210e+03,8.590000,4.779000e+01,1.038400e+02,2.627000e+02,1.633431e+04
Longitude,21759.0,1.136808e+02,9.857587e+00,96.910522,1.061090e+02,1.134177e+02,1.212011e+02,1.386960e+02
Latitude,21759.0,-2.731868e+00,3.608264e+00,-8.682205,-6.204699e+00,-2.461746e+00,2.120369e-01,4.225615e+00
New Cases per Million,21759.0,2.939303e+01,6.994109e+01,0.000000,1.750000e+00,8.160000e+00,2.626000e+01,1.348130e+03
Total Cases per Million,21759.0,6.183651e+03,1.028812e+04,0.010000,4.159150e+02,2.727460e+03,7.374120e+03,7.966379e+04
New Deaths per Million,21759.0,8.527267e-01,2.277310e+00,0.000000,0.000000e+00,1.800000e-01,7.500000e-01,6.380000e+01
Total Deaths per Million,21759.0,1.635422e+02,2.541958e+02,0.000000,1.088000e+01,7.355000e+01,1.958500e+02,1.533980e+03
Total Deaths per 100rb,21759.0,1.635419e+01,2.541960e+01,0.000000,1.090000e+00,7.350000e+00,1.958500e+01,1.534000e+02
Growth Factor of New Cases,20572.0,1.395671e+00,3.080207e+00,0.000000,6.500000e-01,9.900000e-01,1.330000e+00,1.750000e+02
Growth Factor of New Deaths,19292.0,1.074145e+00,1.578502e+00,0.000000,6.600000e-01,1.000000e+00,1.000000e+00,1.345000e+02

In [52]:
covid_df[obj_columns].describe().T

                     count unique            top   freq
Date                 21759    643      1/16/2021     35
Location ISO Code    21759     35          ID-JK    642
Location             21759     35    DKI Jakarta    642
Location Level       21759      2       Province  21117
Province             21117     34    DKI Jakarta    642
Country              21759      1      Indonesia  21759
Continent            21759      1           Asia  21759
Island               21117      7       Sumatera   6208
Time Zone            21117      3      UTC+07:00  11245
Special Status        3123      3  Daerah Khusus   1854
Case Fatality Rate   21759   1316          0.00%    443
Case Recovered Rate  21759   6067          0.00%    258

In [53]:
covid_df.isnull().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
City or Regency                21759
Province                         642
Country                            0
Continent                          0
Island                           642
Time Zone                        642
Special Status                 18636
Total Regencies                    0
Total Cities                     614
Total Districts                    0
Total Urban Villages             617
Total Rural Villages             642
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1187
Growth Factor of New Deaths     2467
dtype: int64

## Data Cleaning

From previous data exploration, theres one column which didn't have any data. So we are going to drop that column.

In [54]:
covid_df = covid_df.drop(columns=['City or Regency'], axis=1)
covid_df.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,41,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,105.13%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,41,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,100.00%,1.0,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,2,0,3,...,0.511648,0.16,0.33,0.0,0.00,0.00,0.00%,150.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,41,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,95.35%,1.0,1.0

In [55]:
num_columns = covid_df.select_dtypes(include=np.number).columns.tolist()

Recollecting all number columns after dropping "City or Regency" column

## Answers

---

### 1. Finding measure of tendency from the dataset

In [56]:
mean = round(covid_df[num_columns].mean().rename('Mean'),2)
median = round(covid_df[num_columns].median().rename('Median'),2)
mode = covid_df[num_columns + obj_columns].mode(dropna=True).iloc[0].rename('Mode')


central_tendency = pd.concat([mean, median,mode], axis=1)
central_tendency

                                    Mean      Median           Mode
New Cases                         391.29       41.00            0.0
New Deaths                         13.22        1.00            0.0
New Recovered                     377.31       31.00            0.0
New Active Cases                    0.76        0.00            0.0
Total Cases                     85259.97    10780.00            2.0
Total Deaths                     2648.29      283.00            1.0
Total Recovered                 76712.60     8745.00            0.0
Total Active Cases               5899.08      919.00            1.0
Total Regencies                    24.16       11.00           12.0
Total Cities                        5.87        2.00            1.0
Total Districts                   420.44      169.00           44.0
Total Urban Villages              508.74      175.00           35.0
Total Rural Villages             4490.35     1591.00        74953.0
Area (km2)                     111241.78    42013.00          664.0
Population                   15478174.01  4216171.00     10846145.0
Population Density                744.99      103.84         138.34
Longitude                         113.68      113.42     106.836118
Latitude                           -2.73       -2.46      -6.204699
New Cases per Million              29.39        8.16            0.0
Total Cases per Million          6183.65     2727.46           0.33
New Deaths per Million              0.85        0.18            0.0
Total Deaths per Million          163.54       73.55            0.0
Total Deaths per 100rb             16.35        7.35            0.0
Growth Factor of New Cases          1.40        0.99            1.0
Growth Factor of New Deaths         1.07        1.00            1.0
Date                                 NaN         NaN       1/1/2021
Location ISO Code                    NaN         NaN          ID-JK
Location                             NaN         NaN    DKI Jakarta
Location Level                       NaN         NaN       Province
Province                             NaN         NaN    DKI Jakarta
Country                              NaN         NaN      Indonesia
Continent                            NaN         NaN           Asia
Island                               NaN         NaN       Sumatera
Time Zone                            NaN         NaN      UTC+07:00
Special Status                       NaN         NaN  Daerah Khusus
Case Fatality Rate                   NaN         NaN          0.00%
Case Recovered Rate                  NaN         NaN          0.00%

Table above giving information about central tendency for every columns inside the dataset. Theres value that giving information about numerical data for example New Cases, New Deaths, New Recovered etc. These column giving us a valid central tendency. Different cases with Longitude and Latitude. These two columns are categorical which means that mean, median, and mode is just giving false information. Because Latitute or Longitude doesn't have any central tendency.

### 2. Find Measure of Variance from the dataset

In [57]:
variance = covid_df[num_columns].var().rename('Variance')
stdev = covid_df[num_columns].std().rename('Standard Deviation')


Measure_of_variance = pd.concat([variance, stdev], axis=1)
Measure_of_variance

                                 Variance  Standard Deviation
New Cases                    4.303762e+06        2.074551e+03
New Deaths                   5.849591e+03        7.648262e+01
New Recovered                3.996251e+06        1.999063e+03
New Active Cases             8.783692e+05        9.372135e+02
Total Cases                  1.358020e+11        3.685133e+05
Total Deaths                 1.386744e+08        1.177601e+04
Total Recovered              1.158692e+11        3.403957e+05
Total Active Cases           7.572460e+08        2.751810e+04
Total Regencies              4.720826e+03        6.870827e+01
Total Cities                 2.713074e+02        1.647141e+01
Total Districts              1.437646e+06        1.199019e+03
Total Urban Villages         2.042406e+06        1.429128e+03
Total Rural Villages         1.599607e+08        1.264756e+04
Area (km2)                   1.026399e+11        3.203746e+05
Population                   2.010244e+15        4.483574e+07
Population Density           7.525200e+06        2.743210e+03
Longitude                    9.717202e+01        9.857587e+00
Latitude                     1.301957e+01        3.608264e+00
New Cases per Million        4.891756e+03        6.994109e+01
Total Cases per Million      1.058455e+08        1.028812e+04
New Deaths per Million       5.186143e+00        2.277310e+00
Total Deaths per Million     6.461548e+04        2.541958e+02
Total Deaths per 100rb       6.461558e+02        2.541960e+01
Growth Factor of New Cases   9.487678e+00        3.080207e+00
Growth Factor of New Deaths  2.491670e+00        1.578502e+00

In [67]:
np.argmax(Measure_of_variance['Standard Deviation'])

14

Table above summarize about variance and standard deviation for each numbers columns. most of them are within the range of +3 which is good because the data more likely to become normal distribution. The most variance in standard deviation is New Deaths and Total Regencies, both columns are having more spread data because their standard deviation is 0.764 and 0.687 respectively.